### ISSUE TITLE
Other issue with symlinks

### ISSUE THREAD

**Issue by julien-f** [tivac/modular-css#108]
The setup is a bit different from #105 but it may be related.

I have updated the repo [julien-f/modular-css-issue-105](https://github.com/julien-f/modular-css-issue-105) to reflect this issue.

**Comment by tivac** [comment]
I will take a look at this in a few hours.

**Comment by tivac** [comment]
It's because browserify doesn't apply the transform to the files in `common` since they are symlinked via `node_modules`, which has special meaning for browserify. Since no transform is applied to the CSS it never gets added to the `modular-css` dependency graph and thus blows up further on.

I can fix this by adding a `global` option to the plugin so it will apply the transform globally, but I think this has serious potential for side-effects. Browserify itself recommends avoiding global transforms whenever possible:

> **Use global transforms cautiously and sparingly**, since most of the time an ordinary transform will suffice. You can also not configure global transforms in a package.json like you can with ordinary transforms.

Instead have you looked into using [`opts.paths`](https://github.com/substack/node-browserify#browserifyfiles--opts)? There's no CLI exposed for it so you'd need to write a small wrapper around the browserify API, but it's pretty simple and seems way less brittle.

**Comment by tivac** [comment]
I implemented the `global` option in [`issues/108`](https://github.com/tivac/modular-css/tree/issues/108) but I'm not super-interested in merging it right now because I think it's a trap.

Interested in whether or not it works like you expect on a real app though!

Should just need to change your browserify invocation to something more like this:

`-p [ modular-css/browserify --css build.css --global ]`

**Comment by julien-f** [comment]
You're right, I though that because the files were not really in a `node_modules` directory, this rule would not apply but indeed I was wrong.

Thanks for the solution using `paths`, it works perfectly!
