### ISSUE TITLE
after hook error using browserify CLI

### ISSUE THREAD

**Issue by Bondifrench** [tivac/modular-css#148]
In npm and using browserify, I try to use [autoprefixer](https://github.com/postcss/autoprefixer) in combination with `modular-css`, with this script in npm
````
"build": "browserify source/js/app.js -p [modular-css/browserify --after autoprefixer --css public/css/bundle.css ] -o public/js/bundle.js"
````
is that possible && what's wrong with my syntax?

I get an error: `Error: autoprefixer is not a PostCSS plugin` which it is.

**Comment by tivac** [comment]
Looking (but on a ✈️) so no promises!

**Comment by tivac** [comment]
Ok so the problem is that the browserify plugin gets passed this:

```js
"after": "autoprefixer"
```

and tries to pass that as a postcss plugin. PostCSS doesn't accept string plugins, so it doesn't work. I could do some work to enable that but given the various ways PostCSS plugins expect you to call them I would likely say that it'd be better to write a small script to wrap browserify and apply the `modular-css` plugin via code.

If there's someone out there providing a robust way to do this please link it and I'll see how much work it wold be to add!

**Comment by Bondifrench** [comment]
It seems [css-modulesify](https://github.com/css-modules/css-modulesify) is doing it when you look at the section PostCSS Plugins, I believe they do it [here](https://github.com/css-modules/css-modulesify/blob/master/index.js#L116)
