### ISSUE TITLE
Would be nice if this supported // comments.

### ISSUE THREAD

**Issue by ctcleary** [tivac/modular-css#198]
Yup.

**Comment by tivac** [comment]
https://github.com/zoubin/postcss-comment looks like it what you want.

I'd use it as a [`before`](https://github.com/tivac/modular-css/blob/master/docs/api.md#before) so it could clean up the comments before further parsing happened. `modular-css` itself shouldn't care if PostCSS doesn't, so you could certainly add it as an `after` if you preferred, but `before` is simpler.

**Comment by ctcleary** [comment]
Sorry. I was about to add some more context as you replied: My Sublime Text 3 read the syntax of `modular-css` as LESS, so the comment hotkey defaults to using `//`. 

It's certainly something we could add to the build, but I figured it might be a way to make `modular-css` a little easier to use straight out of the box.

**Comment by tivac** [comment]
I feel pretty strongly that `modular-css` should do `modular-css` things, and other PostCSS plugins should handle other things like nesting, `//` comments, `calc()`, etc.

`modular-css` includes postcss-url mostly because it's reading in files and writing bundled output to a new location, so it really **needs** to be able to smartly update image references. Otherwise the intent is to provide the necessary hooks to allow end-users to wire up whatever PostCSS plugin functionality they need and try to not add any more code or dependencies than absolutely necessary.

I agree that having comments default to `//` sounds annoying, and have zero issues with any of our `modular-css`-using build scripts updated to also use `postcss-comment`.

**Comment by ctcleary** [comment]
Okay, sounds good.
