### ISSUE TITLE
Split into separate packages : core & tool-plugins

### ISSUE THREAD

**Issue by ndelangen** [tivac/modular-css#214]
If webpack support is going to be added, (👏🏻🎉💯), this package will then have a '(dev) dependency' on webpack, browserify, & rollup. 

Should this package be split into a core module (build-tool independent) and the respective tool-plugins be in their own package? possibly even their own repo. Maybe something like https://lernajs.io/ could be of help?

# Reasons for doing this:

**install speed**
Installation can take a very long with so many large dependencies. And it makes sense to only install what is required for use.

**semver**
When 1 of the build-tools introduces a new version with a breaking change, a breaking change for this entire package might be needed, when in fact, the core and the other build-tool plugins remained unchanged?

**Comment by tivac** [comment]
`modular-css` exists in part because I found the scattered-amongst-10-repos approach of CSS Modules to be a nightmare when trying to debug issues I was having.

The downsides of a single package:

1. Installing multiple build tools for dev
2. Shipping things like `rollup-pluginutils` or `sink-transform` in all versions

The semver stuff isn't a big concern for me. I'm already being pretty aggressive about bumping the minor version number every time anything changes. It'll hit 1.0.0 before too long but I don't find bumping the major version number any scarier.

I like the idea behind lerna but haven't played with it enough to know if I like it or not and there's a non-trivial amount of work involved with switching to that format. Since the downsides of a single package are relatively small so far I haven't seriously considered it. If adding webpack truly makes dev installs super-painful or requires that we ship a ton more dependencies when installing for end-users I'll circle back around on the decision.

(that also assumes that I'll ever force myself to finish webpack support, which atm isn't guaranteed at all)

**Comment by ndelangen** [comment]
I understand, I've only just started experimenting with lerna. 

Single repo, multiple packages is a good choice in the long run I think...
