### ISSUE TITLE
How to use as postcss plugin?

### ISSUE THREAD

**Issue by gartz** [tivac/modular-css#221]
With webpack 2 we add postcss plugins in the `postcss.config.js` file and that's all... However I couldn't make this work out-of-the-box. Am I doing something wrong or the support is not implemented yet?

**Comment by tivac** [comment]
Right now you can't.

Due to how you can use `@value` or `composes:` to pull in information from another file it needs to be able to process files in an unknown-until-runtime order. `modular-css` also needs to be able to run it's own specific plugins in a specific order on those unknown files.

I haven't been able to come up with a way to represent/contain that within the PostCSS API yet. If you've got some experience & time I'd love for some pointers because I've banged my head against that a few times and haven't made any progress.

**Comment by gartz** [comment]
Checkout postcss-next it might help you, because they also support plugins and have support to Includes tags, and they work as a postcss plugin. Their code might have what you need I hope. Best luck with your project, I think it's promising :) you could call it CSS-modules-next since you're adding things that are being evaluated by the official CSS-modules team.

--
Gabriel Reitz Giannattasio
gabriel@loadin.com.br
+1 (240) 803-1986

**Comment by tivac** [comment]
Just kidding, a fresh set of eyes and this looks potentially doable now that I know PostCSS better.

Working on it in the [`postcss-plugin` branch](https://github.com/tivac/modular-css/tree/postcss-plugin).
