### ISSUE TITLE
A class is showing up earlier in the generated file than the one it is composing

### ISSUE THREAD

**Issue by Ryan-McMillan** [tivac/modular-css#265]
This is causing the composed class's css properties to take precedence over the one composing it.  We talked about this and I wasn't able to get a simplified repro.  

.quantityListShow in contacts.css is composing .dropdown in dropdown.css, but .dropdown is further down in the generated file.

**Comment by tivac** [comment]
It's caused by a quirk of the rollup plugin 😓 

https://github.com/tivac/modular-css/blob/558e2a5f20df4386d9e8f1689598aa1a1449a298/packages/rollup/rollup.js#L42

In order to avoid caching issues w/ stale files the rollup plugin removes each file before processing it. It doesn't remove any of its dependents in an attempt to not break the graph but for some reason it's not working in this case.

`dropdown.css` gets processed twice, and the second time it gets lost as a dependency of `contacts.css`.

**Comment by tivac** [comment]
https://github.com/tivac/modular-css/pull/193 is the PR that added that behavior, nice to see I wasn't happy about it back then either.

I think I can work around this by **not** removing the node from the dependency graph, just the `files` object.

**Comment by tivac** [comment]
@Ryan-McMillan this is fixed in `modular-css-rollup@4.1.4`
