### ISSUE TITLE
Why section should be more descriptive

### ISSUE THREAD

**Issue by TrySound** [tivac/modular-css#305]
It would be good to have some peace of community, which can help to fix some bugs and which have same problems with css-modules like you, @tivac.

We need to describe why this packages better then css-modules.

**Comment by TrySound** [comment]
Maybe some facts and comparisons

**Comment by TrySound** [comment]
webpack / rollup
* es modules support

**Comment by tivac** [comment]
Ah, this is a tricky one. I've been trying very hard not to push `modular-css` at the expense of CSS Modules. It seemed to be me be in bad taste. A more complete comparison is probably fine but I haven't spent much time thinking about it.

I appreciate any feedback on this one, I'm happy to revamp the section but want to avoid even the appearance of crapping on CSS Modules since the debt owed to that project is so huge.

**Comment by tivac** [comment]
Haven't heard back in a while, closing.
