### ISSUE TITLE
Warning when :global rule is applied on a class with a dash

### ISSUE THREAD

**Issue by getkey** [tivac/modular-css#312]
Like last time, you can use [my repository](https://github.com/getkey/modular-css-bug/tree/0659df21633cfe8aa9493a9282fa881ad54a8075) to reproduce the bug with `npm run watch`. :-)

It seems the CSS is properly built even though there is this warning.

**Comment by tivac** [comment]
Yeah, that's intended. [`page-text` isn't a valid JS Identifier](https://mothereff.in/js-variables#page-text) so it complains.

If you want to disable the warning you have two options.

1. Set `namedExports` to `false` in the [webpack loader options](https://github.com/tivac/modular-css/blob/master/docs/webpack.md#namedexports). This will cause named ES2015 imports from CSS files to no longer work, only the default import will be available.

```js
// This won't work
import { app } from "./index.css";

// This still will though
import css from "./index.css";

css["page-text"] // "page-text"
```

2. You could also set `exportGlobals` to `false` in the [plugin options](https://github.com/tivac/modular-css/blob/master/docs/api.md#exportglobals). This will prevent any rules wrapped in `:global(...)` from being exported at all. I prefer having `global`s as part of the exports so that all CSS styling happens in the same path but if you don't need it this is a viable option.

**Comment by getkey** [comment]
Oh that makes sense!
Alright, thanks!
