### ISSUE TITLE
Watchify breaks relative file path rewriting

### ISSUE THREAD

**Issue by tivac** [tivac/modular-css#35]
It keeps re-updating relative file paths, which makes them very, very broken.

**Comment by tinchoz49** [comment]
Hi @tivac! i'm working with you library and is great! good job! But i think that the rebase URLs has to be an optional feature because for example: i don't like how postcss-url works and i prefer use postcss-copy but both execute a rebase url in the process. 

What do you think? maybe have something like ```rebase: true (default)```

**Comment by tinchoz49** [comment]
Or maybe delegate this feature to the end developer. This can be easier customize using the option ```before```

**Comment by tivac** [comment]
I can probably add a config option to make the `postcss-url` usage overridable, but could you first file this as a separate issue please?

**Comment by tinchoz49** [comment]
yes, of course.
