### ISSUE TITLE
Support composing "compiled" files

### ISSUE THREAD

**Issue by jquense** [tivac/modular-css#670]
### Feature Use Case

When consuming a library that uses modular-css it'd be nicer if the consumer could continue to treat that library as modular, even if it's already been compiled to `json` and `css`.

```css
.my-button {
  composes: btn from 'ui-library/Button.css';

 ...
}
```

### Feature Proposal

I think you'd need support for importing from `json` files, as well as a convention finding the paired file.

Quick brainstorming for possible approaches:

- export a special json file of the exports that contain the text of the file, or relative import?
- always compose the `css` file, with a comment containing the original exports?
- some convention that you can always try and resolve a sibling json file and use that if it exists?

**Comment by tivac** [comment]
Probably worthwhile to add a method to `@modular-css/processor` along the lines of `processor.import()` that can import the JSON from a previous build. Then those files would exist in the internal module graph & be trivially usable for referencing from wherever in your CSS. Small wrinkle is ensuring that none of those files are output but that should be... possible.

Not totally clear how you'd indicate that it should use that JSON file to me yet though. First thought is maybe a custom [`resolver`](https://m-css.com/api/#resolvers) but I think I hate that. Something better might be adding a new option like `imports` or something that is an object with keys representing the packages and values pointing to their JSON files.

```js
require("@modular-css/rollup")({
    imports : {
        "ui-library" : require.resolve("ui-library/details.json"),
    },
});
```

Unless we do something wonky like adding a new field to `package.json` there isn't an easy way to resolve to a specific build info json file directly, because lord knows what it might've been named.

**Comment by jquense** [comment]
A lot would depend on how you ship the styles in the library. If it's a single concatanated css file it's maybe easier to wrap some conventions around vs leaving the  individual files (would that even work?)

There is some existing convention for having a package.json `style` field like `main` in the ecosystem. parcel, and others respect it. One thing we could do is embed a path to exports.json in the style file like a source map does:

```css
/*! @modular-css:./exports.json */

.d35df {
 ...
} 
```

Alternatively one could just reference the json file directly in css and have modular-css know how to handle it

```
.my-button {
  composes: btn from 'ui-library/styles.json';
}
```

That seems like maybe the best first step? Nice thing about `json` is you don't really need any additional logic to parse and include the files.

**Comment by tivac** [comment]
Referencing the json directly is an interesting approach, the trick would be that you'd still need to reference the file *in* the JSON that you wanted to compose the class from.

I don't really want to get into webpack-style bundler commands via filepaths like `composes: btn from "ui-lib/styles.json:base/shared/style.css";` or anything because that's a nightmare.

Something like a new @-style rule could maybe work...
