### ISSUE TITLE
Aliases provided in a `<link>` tag for a Svelte 3 file aren't resolved by known build-system aliases

### ISSUE THREAD

**Issue by stffrd** [tivac/modular-css#679]
O' LORD OF MODULAR CSS. 

I'm running into an issue where I'd like to use the aliases that my current rollup configuration knows about to point to a specific `css` file to use in a given Svelte3 component. 

like so:
`<link rel="stylesheet" href="shared/styles/target.css">` 

Normally the way I structure the css is by referencing a stylesheet in the same general directory as the component, such that referencing is as simple as 
`<link rel="stylesheet" href="./target.css">`

However, again, I'm running into the issue when I try to use aliases that my rollup configuration knows about. 

## Expected Behavior

`<link rel="stylesheet" href="shared/styles/target.css">` is resolved properly to point to the correct file, where `shared/` is a convenient alias pointing to another folder in my project. 

## Current Behavior

`<link rel="stylesheet" href="shared/styles/target.css">`  causes an error :

`[!] (plugin svelte) Error: Cannot find module 'shared/styles/target.css'`

## Possible Solution

The resolution of a given `href` should probably be injected with known build time aliases (or at least the resolver should expose an option to provide it with a pairing of aliases to paths to resolve against)

**Comment by tivac** [comment]
Looks like this line

https://github.com/tivac/modular-css/blob/5789b89f0a5fe67295673a1ceada9ab1f5ba4858/packages/svelte/svelte.js#L146

Should actually use the `Processor` instance's `._resolve()` method instead of bare `resolve-from`. `._resolve()` should also be renamed to `.resolve()` so it's available to any API consumers that want it.

https://github.com/tivac/modular-css/blob/5789b89f0a5fe67295673a1ceada9ab1f5ba4858/packages/processor/processor.js#L73

**Comment by tivac** [comment]
This is fixed in `@modular-css/svelte@25.2.0`
